// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpo_ORIwa9lJ2U2NHrCkzwjAuYewvcyTo',
    appId: '1:830679105017:web:20fb3a6057f29f428a5128',
    messagingSenderId: '830679105017',
    projectId: 'fooddelivery-e2643',
    authDomain: 'fooddelivery-e2643.firebaseapp.com',
    databaseURL: 'https://fooddelivery-e2643-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddelivery-e2643.appspot.com',
    measurementId: 'G-RSNMCGBTJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMm9WHhqjBtsAsMXzjrHoLKCLvdNcCwA0',
    appId: '1:830679105017:android:66e877c469b0845a8a5128',
    messagingSenderId: '830679105017',
    projectId: 'fooddelivery-e2643',
    databaseURL: 'https://fooddelivery-e2643-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddelivery-e2643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVSzpRm-PRj7_KHQvOPVvekVsJ-s-0Ow',
    appId: '1:830679105017:ios:c93c4aa7adcc52ca8a5128',
    messagingSenderId: '830679105017',
    projectId: 'fooddelivery-e2643',
    databaseURL: 'https://fooddelivery-e2643-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddelivery-e2643.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVSzpRm-PRj7_KHQvOPVvekVsJ-s-0Ow',
    appId: '1:830679105017:ios:c93c4aa7adcc52ca8a5128',
    messagingSenderId: '830679105017',
    projectId: 'fooddelivery-e2643',
    databaseURL: 'https://fooddelivery-e2643-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddelivery-e2643.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpo_ORIwa9lJ2U2NHrCkzwjAuYewvcyTo',
    appId: '1:830679105017:web:7b68b10e871065c78a5128',
    messagingSenderId: '830679105017',
    projectId: 'fooddelivery-e2643',
    authDomain: 'fooddelivery-e2643.firebaseapp.com',
    databaseURL: 'https://fooddelivery-e2643-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddelivery-e2643.appspot.com',
    measurementId: 'G-D2ZZW5236D',
  );
}
